### ISSUE TITLE
GeoServer does not permit an 'OR' cql filter for layer 'transit_shapes_with_routes'

### ISSUE THREAD

**Issue by richardforsterNVBW** [mobidata-bw/ipl-orchestration#113]
When I try to filter the transit shapes, I can only filter route_type individually, e.g.: `route_type = 0`.

Whenever I attempt to combine two route_types - e.g. `route_type = 3 OR route_type = 2` - I get the following error:

![image](https://github.com/mobidata-bw/ipl-orchestration/assets/160242313/cdb2588b-ca3b-4a66-9be5-db9e1dfd2906)

The same is true when combining other route_types or all of them at the same time. 

So far, I only have detected this issue with transit_shapes_with_routes.

**Comment by hbruch** [comment]
This ressembles the issue we encountered with enum types a while ago. For now, a work around would be to use `route_type >=2 and route_type <=3`. I have a suspicion that multiple 'equal or's might be transformed by geoserver into an `IN ('2','3')` query, which via sql results in the same exception:

```sql
SELECT * FROM api.routes WHERE route_type IN ('2','3') LIMIT 1;
ERROR:  operator is not unique: api.route_type_val = api.route_type_val
LINE 1: select * from api.routes where route_type in ('2','3') limit...

SELECT * FROM api.routes WHERE route_type IN ('2','3') LIMIT 1;
```

whereas this query executes fine:

```sql
SELECT * FROM api.routes WHERE route_type = '3' OR route_type='2' LIMIT 1;
  route_id   | agency_id | route_short_name | route_long_name | route_desc | route_type | route_url | route_color | route_text_color | route_sort_order
-------------+-----------+------------------+-----------------+------------+------------+-----------+-------------+------------------+------------------
 bus-2-001-1 | bus-8533  | 001              |                 |            | 3          |           |             |                  |
(1 row)
```

@derhuerst could you have a look please?
