### ISSUE TITLE
RegioRad: wrong formFactor for cargo pedelec

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#114]
RegioRad specifies the following vehicle type:

<img width="271" alt="grafik" src="https://github.com/mobidata-bw/ipl-orchestration/assets/2187389/568aa983-66d7-4e88-8d61-ef86206f8f76">

Instead of `bicycle`, the form_factor should be `cargo_bicycle`.

**Comment by ThorstenFroehlinghaus** [comment]
RegioRad still uses GBFS 2.2. I asked them to update to GBFS 2.3 and to provide form_factor cargo_bicycle.

**Comment by ThorstenFroehlinghaus** [comment]
RegioRad now provides GBFS 2.3, and the form_factor is set to cargo_bicycle.
