### ISSUE TITLE
Geoserver: WMS GetLegendGraphic doesn't render some labels correctly

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [mobidata-bw/ipl-orchestration#117]
Please ensure that words like "Straßen" and "verfügbar" are displayed correctly. "Kreisnetzz" should be changed to "Kreisnetz". The sharing_vehicles layer should obtain a text like "Free-Floating-Fahrzeuge". Please add texts for the roadworks layer.

**Comment by derhuerst** [comment]
@ThorstenFroehlinghaus Can you provide URLs that demonstrate the issues described? That would be great! 🙏

**Comment by ThorstenFroehlinghaus** [comment]
Here is an example URL:
https://api.mobidata-bw.de/geoserver/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=roadworks
For the other layers just take their name as argument for the layer parameter.
