### ISSUE TITLE
liemobil_liechtenstein GBFS feed: retrieving geofencing_zones results in timeout

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#122]
Endpoint https://api.mobidata-bw.de/sharing/gbfs/liemobil_liechtenstein/geofencing_zones results in 404.

Reason is that this feed can't be retrieved from upstream:

```
curl -H 'Authorization: <emailadress>' https://gbfs.prod.sharedmobility.ch/v2/gbfs/liemobil_liechtenstein/geofencing_zones
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
```

@ThorstenFroehlinghaus could you please contact the data provider?

**Comment by ThorstenFroehlinghaus** [comment]
I informed sharedmobility.ch about this issue.

**Comment by ThorstenFroehlinghaus** [comment]
sharedmobility.ch fixed this issue, https://[gbfs.prod.sharedmobility.ch/v2/gbfs/liemobil_liechtenstein/geofencing_zones?Authorization=mobidatabw-ipl@nvbw.de](https://gbfs.prod.sharedmobility.ch/v2/gbfs/liemobil_liechtenstein/geofencing_zones?Authorization=mobidatabw-ipl@nvbw.de) returns an emtpy FeatureCollection.
