### ISSUE TITLE
GeoServer: Encoding issues with layer legends

### ISSUE THREAD

**Issue by richardforsterNVBW** [mobidata-bw/ipl-orchestration#124]
Some of the layers have issues with ä, ö, ü and ß. I noticed that `mdbw_parking_site_default` which also uses this letters visualized the legend without any problems. Is there a reason why some layer styles are defined as UTF-8 while others as ISO-8859-1 which causes this problem?

**Comment by hbruch** [comment]
It should be UTF-8 for all. I'll fix this.
