### ISSUE TITLE
Parking file from Reutlingen cannot be pushed

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [mobidata-bw/ipl-orchestration#131]
On my local windows machine, the command

py push-client.py -u https://test-ipl.mobidata-bw.de/park-api reutlingen ..\..\Parkhäuser.csv

fails with the following message:

Invalid input data: {'error': {'code': 'invalid_input', 'message': 'Invalid input: cannot find header key id'}}

The other files (vrs-p-r, neckarsulm, pforzheim) can be pushed correctly.

**Comment by the-infinity** [comment]
The old CSV file by Reultingen has an `id` in it: https://github.com/ParkenDD/parkapi-sources-v3/blob/main/tests/converters/data/reutlingen.csv?plain=1 . Did they change something?

**Comment by ThorstenFroehlinghaus** [comment]
We used different files. https://nvbwde.sharepoint.com/:f:/s/MobiDataBW-Integrationsplattform/Eodx3eN508pKmf0-J2yieMIBlxGoeWcA3vJULa7zu9LXBw?e=SFbHq6 contains 4 files for Reutlingen. You are using "Parkflächen.csv", right?
The other 3 files were not pushed, right?

**Comment by the-infinity** [comment]
The converter mapping developed by @AbdullahiFatola just supported the CSV with `id` in header: https://github.com/ParkenDD/ParkAPI2-sources/pull/76/files#diff-a080ea0d8d597fc31d8de6c23bc0df4ff9848db8c2604af13ff653c36fdf595eR79 , so yes, files without `id` in header cannot and have not been pushed.

**Comment by ThorstenFroehlinghaus** [comment]
ok, I wrongly used the original files from Reutlingen. the files which have been postprocessed by @AbdullahiFatola can be pushed without problems.
