### ISSUE TITLE
GeoServer: attributes

### ISSUE THREAD

**Issue by richardforsterNVBW** [mobidata-bw/ipl-orchestration#133]
## Capacity attribute
The Cantamen carsharing feeds contain a `capacity` attribute:

```
 "station_id": "SMT:Station:2671",
                "name": "Felix-Dahn-Str.",
                "lat": 48.74955038,
                "lon": 9.17539045,
                "capacity": 1,
                "rental_uris": {
                    "android": "cantamen-interapp-csd://add_booking?openPlace=2671",
                    "ios": "cantamen-interapp-csd://add_booking?openPlace=2671",
                    "web": "https://ewi3.cantamen.de/?openPlace=2671"
                }
```
Can we add this attribute for the layer `MobiData-BW:sharing_stations_car`? From my understanding, the sql statemen must be edited in this case by something like `s.capacity`.

```
SELECT s.feed_id, s.station_id, s.name, st.num_cars_available num_vehicles_available, s.rental_uris_android, s.rental_uris_ios, s.rental_uris_web, st.last_reported, s.geometry
FROM sharing_stations s
 JOIN sharing_station_status st ON s.station_id=st.station_id
WHERE st.num_cars_available >= 0
```

Maybe you could show me how to add it in a hands-on.

## Renaming of num_vehicles_available
Within the GBFS feeds the attribute `num_bikes_available` exists. Wouldn't it be better to have consistent names?

**Comment by hbruch** [comment]
Has been solved with https://github.com/mobidata-bw/ipl-orchestration/commit/38304f67d8947740de8f46c8d9738f360cf84ec2.

Note that though `num_bikes_available` is the GBFSv2.3 property, GBFSv3.0 changed this to the more generic `num_vehicles_available`, which we use here for all form factors.
