### ISSUE TITLE
Dagster: Missing sharing stations in data base and GeoServer

### ISSUE THREAD

**Issue by richardforsterNVBW** [mobidata-bw/ipl-orchestration#142]
We observed a bug that some sharing stations are not displayed in the GeoServer. I checked the PostgreSQL data base and did not find these stations as well. This means that Dagster does not write the stations into the data base in the first place.

The pattern behind the missing stations seems to be following one: 
If the attribute `vehicle_types_available` is empty in the gbfs feeds no station is written into the data base. 

For instance, these two stations DID NOT appear on the map or in the data base when I search for them this morning:

```
           {
                "station_id": "SWT:Station:468271775",
                "num_bikes_available": 0,
                "vehicle_types_available": [],
                "is_installed": true,
                "is_renting": true,
                "is_returning": true,
                "last_reported": 1714463902
            },
	    {
                "station_id": "DER:Station:5a530bb20d1dff00063bd779",
                "num_bikes_available": 0,
                "vehicle_types_available": [],
                "is_installed": true,
                "is_renting": true,
                "is_returning": true,
                "last_reported": 1714463881
            },	
```

On the other hand, these two - which contain specific information on the `vehicle_types_available` are not skipped: 

```
           {
                "station_id": "NBK:Station:15430610",
                "num_bikes_available": 0,
                "vehicle_types_available": [
                    {
                        "vehicle_type_id": "NBK:VehicleType:150",
                        "count": 0
                    }
                ],
                "num_docks_available": 5,
                "is_installed": true,
                "is_renting": true,
                "is_returning": true,
                "last_reported": 1714464619
            },
	   {
                "station_id": "SWT:Station:1207613767",
                "num_bikes_available": 0,
                "vehicle_types_available": [
                    {
                        "vehicle_type_id": "SWT:VehicleType:opel_corsa",
                        "count": 0
                    }
                ],
                "is_installed": true,
                "is_renting": true,
                "is_returning": true,
                "last_reported": 1714463902
            },
```

**Comment by hbruch** [comment]
As a GBFS feed may include multiple formFactors, the import aims to classify a station's formFactor (is it a car sharing, bike sharing etc station) by deducing it from vehicle's potentially available at this station.

Could you specify the expected behavior in case no vehicle is stated as being potentially available at a station?

**Comment by hbruch** [comment]
Has been solved with https://github.com/mobidata-bw/ipl-orchestration/commit/38304f67d8947740de8f46c8d9738f360cf84ec2
