### ISSUE TITLE
Feed lime_zug can't be ingested by lamassu

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#18]
# How does this error show up?
lamassu shows white label error page for http://10.70.172.11:8500/gbfs/lime_zu/gbfs, http://10.70.172.11:8500/validation/systems/lime_zu returns only `[]`

# Feed source information?
## Feed source
Feed URL: https://data.lime.bike/api/partners/v2/gbfs/zug/gbfs.json
The feed is openly available, no credentials required.
## Feed validity
Validator URL: https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fdata.lime.bike%2Fapi%2Fpartners%2Fv2%2Fgbfs%2Fzug%2Fgbfs.json

The feed is not valid, the validator reports `must have required property 'vehicle_types_available'`

**Comment by ThorstenFroehlinghaus** [comment]
I removed this feed because it is empty and defect - even at https://gbfs.prod.sharedmobility.ch/v2/gbfs/lime_zug/gbfs
