### ISSUE TITLE
GBFS feed link_zurich can't be ingested

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#19]
# How does this error show up?
lamassu shows white label error page for http://10.70.172.11:8500/gbfs/link_zurich/gbfs, http://10.70.172.11:8500/validation/systems/link_zurich returns only `[]`

# Feed source information?
## Feed source
Feed URL: https://mds.linkyour.city/gbfs/ch_zurich/gbfs.json
The feed is openly available, no credentials required.
## Feed validity
Validator URL: https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fmds.linkyour.city%2Fgbfs%2Fch_zurich%2Fgbfs.json

The feed is not valid, the validator reports `Sorry, this version is not yet implemented or not detectable !`

**Comment by ThorstenFroehlinghaus** [comment]
I removed this feed because it is empty and defect.
