### ISSUE TITLE
ZEUS vehicles listed in multiple feeds

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#229]
Sharing provider ZEUS has overlapping feeds. I.e. feeds `zeus_hemmingen` and `zeus_ludwigsburg`, both contain the vehicles located in i.e. Schwieberdingen and Korntal.

Consequences:
1. The same vehicle is listed twice
2. creating a single column primary key on `vehicles.vehicle_id` is not possible, thus blocking WFS 2.0 support for paginated requests. 

<img width="886" alt="image" src="https://github.com/user-attachments/assets/71ba7e79-e530-4c7c-8beb-5a5c615b9004">

As vehicles are contained twice already, I suggest to change the lamassu codespace to e.g. `ZEH` for Hemmingen, to avoid ID clashes.

**Comment by ThorstenFroehlinghaus** [comment]
Zeus told us that they will adjust the feeds for ludwigsburg and hemmingen. Until then, we will deactivate zeus_hemmingen. Most of its vehicles are contained in zeus_ludwigsburg anyway.
