### ISSUE TITLE
Request limits for rideatom services (roxy and yoio) exceeded

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#74]
Currently, requesting GBFS feeds for YOIO and Roxy often fails due to `429  {"message": "You have reached your request limit. Please try again later."}` responses.

```json
{"serviceContext":{"service":"lamassu"},"message":"System information feed was null for provider=FeedProvider{systemId='roxy_freiburg', operatorId='RXY:Operator:roxy', operatorName='Roxy', codespace='RXY', url='https://roxy.rideatom.com/gbfs/v2_2/en/gbfs?id=XXX', language='en', authentication=null, excludeFeeds=null, aggregate=true, vehicleTypes=null, pricingPlans=null}\n","severity":"WARN","reportLocation":{"filePath":"org.entur.lamassu.mapper.feedmapper.SystemInformationFeedMapper","lineNumber":"47","functionName":"map"}}
{"serviceContext":{"service":"lamassu"},"message":"System information feed was null for provider=FeedProvider{systemId='yoio_freiburg', operatorId='YOO:Operator:yoio', operatorName='Yoio', codespace='YOO', url='https://yoio.rideatom.com/gbfs/v2_2/en/gbfs?id=XXX', language='en', authentication=null, excludeFeeds=null, aggregate=true, vehicleTypes=null, pricingPlans=null}\n","severity":"WARN","reportLocation":{"filePath":"org.entur.lamassu.mapper.feedmapper.SystemInformationFeedMapper","lineNumber":"47","functionName":"map"}}
```

@ThorstenFroehlinghaus could you get in touch with them regarding the request limit? If only a limited number of requests is allowed, it would be helpfull if the provider published the feeds with meaningful `ttl` values. Currently, all feeds have a ttl equal to 0, what means they should be requested continuously by clients. If the providers won't update the feeds, you might consider patching the ttl via the transformer-proxy like we already do for [some feeds](https://github.com/mobidata-bw/ipl-proxy/blob/main/app/converters/db_connect_ttl_fixes.py).

**Comment by ThorstenFroehlinghaus** [comment]
Roxy told us, that they are not willing to increase the rate limit.
@hbruch : Can we use different request rates for prod/dev/test? For dev/test, hourly should be sufficient.

**Comment by hbruch** [comment]
Lamassu has a config setting `org.entur.lamassu.feedupdateinterval` which can be set on the different systems. We'll introduce an env-variable (e.g. `LAMASSU_FEED_UPATE_INTERVAL_IN_MS`) which can be used to define this value per system.

However, roxy/yoio deliver all feeds with a ttl of 0, which indicates to fetching systems they should not be cached but always be updated (see section [data latency in the spec](https://gbfs.org/specification/reference/#data-latency)). It would be helpful, if for rather static feeds this could be set to an appropriate value:

<img width="518" alt="grafik" src="https://github.com/mobidata-bw/ipl-orchestration/assets/2187389/c30c3005-118f-4dd4-8b21-8a58d79e0f39">

**Comment by ThorstenFroehlinghaus** [comment]
I asked roxy/yoio to set appropriate ttl values.
