### ISSUE TITLE
Data error: bolt_stuttgart/station_status required key [num_bikes_available] not found

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/ipl-orchestration#77]
The [`station_status` feed](https://dev-ipl.mobidata-bw.de/sharing/gbfs/bolt_stuttgart/station_status) of the `bolt_stuttgart` feed does not provide the mandatory field `num_bikes_available`.

In addition, some stations have outdated `lastReported` timestamps dating from e.g. `Mon May 29 2023 14:27:10 GMT+0000`:

<img width="593" alt="grafik" src="https://github.com/mobidata-bw/ipl-orchestration/assets/2187389/d98cc0d9-c90c-4dc1-8132-b0f91395ddf9">

@ThorstenFroehlinghaus could you please contact the provider, if they could fix the feed. If the feed shows up-to-date availabilty, an only the field `num_bikes_available` is missing, this seems to be deducible from the `vehicle_types_available` array.

**Comment by ThorstenFroehlinghaus** [comment]
Meanwhile, the num_bikes_availble attribute is provided by Bolt. However, the last_reported timestamp is not updated yet.

**Comment by ThorstenFroehlinghaus** [comment]
station_information.is_virtual_station is now set to true to specify that a station a just a parking space. for this reason, the last_reported timestamp must no be updated regularily.
